// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdfVDvl48B4srt3rOfq3ohEVY6kPsX8Y',
    appId: '1:840839434044:web:0b12518bca9480c3679839',
    messagingSenderId: '840839434044',
    projectId: 'expensetracker-d68c5',
    authDomain: 'expensetracker-d68c5.firebaseapp.com',
    storageBucket: 'expensetracker-d68c5.appspot.com',
    measurementId: 'G-CYE33H9WS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANo3ZQvosSMWLR93TOCgpT3UlZHl9OF48',
    appId: '1:840839434044:android:de1686892f819f3d679839',
    messagingSenderId: '840839434044',
    projectId: 'expensetracker-d68c5',
    storageBucket: 'expensetracker-d68c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5uELJa9plYPbYuzR4wcCtSAdS-IfQTfk',
    appId: '1:840839434044:ios:a365f2737fae85cf679839',
    messagingSenderId: '840839434044',
    projectId: 'expensetracker-d68c5',
    storageBucket: 'expensetracker-d68c5.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5uELJa9plYPbYuzR4wcCtSAdS-IfQTfk',
    appId: '1:840839434044:ios:a365f2737fae85cf679839',
    messagingSenderId: '840839434044',
    projectId: 'expensetracker-d68c5',
    storageBucket: 'expensetracker-d68c5.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfdfVDvl48B4srt3rOfq3ohEVY6kPsX8Y',
    appId: '1:840839434044:web:5a3cc54f9f0c0a37679839',
    messagingSenderId: '840839434044',
    projectId: 'expensetracker-d68c5',
    authDomain: 'expensetracker-d68c5.firebaseapp.com',
    storageBucket: 'expensetracker-d68c5.appspot.com',
    measurementId: 'G-1RKHD81802',
  );
}
